mv 01-getting-started.md getting-started.md
mv 02-concepts.md concepts.md
mv 03-developer-reference.md developer-reference.md
mv 04-platform-as-a-service.md platform-as-a-service.md
mv 05-installation.md installation.md
mv 06-administration.md administration.md
mv 07-development--production.md development-production.md
mv 08-security.md security.md
mv 09-supported-databases.md support-matrix.md
mv 10-api.md api.md
mv 11-contribute.md contribute.md
