site_name: Dashjoin Platform Documentation
theme:
  name: material
  custom_dir: overrides

#
# Use version management
# see: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/
extra:
  version:
    provider: mike

#
# Enable code highlighting
#
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: 'index.md'
  - 'getting-started.md'
  - 'concepts.md'
  - 'user-interface.md'
  - 'developer-reference.md'
  - 'i18n.md'
  - 'ai-ml-integration.md'
  - 'installation.md'
  - 'administration.md'
  - 'development-production.md'
  - Security and Access Control: 'security.md'
  - 'support-matrix.md'
  - 'api.md'
  - 'faq.md'
  - 'contribute.md'
  - 'appendix-configurations.md'
  - 'appendix-input.md'
  - 'appendix-jsonata.md'
  - 'appendix-widgets.md'
