### read record
GET http://localhost:8080/rest/jsonapi/northwind/ORDERS/10248
Authorization: Basic admin:djdjdj

### TEST
GET http://localhost:8080/rest/jsonapi/northwind/EMPLOYEES/5
Authorization: Basic admin:djdjdj

### read table
GET http://localhost:8080/rest/jsonapi/northwind/CUSTOMERS
Authorization: Basic admin:djdjdj

