### discover
GET http://localhost:8080/rest/jsonapi/northwind
Authorization: Basic admin:djdjdj

### read record
GET http://localhost:8080/rest/jsonapi/northwind/ORDERS/10248
Authorization: Basic admin:djdjdj

### read table
GET http://localhost:8080/rest/jsonapi/northwind/ORDER_DETAILS
Authorization: Basic admin:djdjdj

### read table / sort (error)
GET http://localhost:8080/rest/jsonapi/northwind/CUSTOMERS?sort=COUNTRY,CITY
Authorization: Basic admin:djdjdj

### read table / sort
GET http://localhost:8080/rest/jsonapi/northwind/CUSTOMERS?sort=-COUNTRY
Authorization: Basic admin:djdjdj

### read table / filter
GET http://localhost:8080/rest/jsonapi/northwind/CUSTOMERS?filter={"CITY":"Berlin"}
Authorization: Basic admin:djdjdj

### read record / fields
GET http://localhost:8080/rest/jsonapi/northwind/ORDERS/10248?fields[ORDERS]=ORDER_DATE,REQUIRED_DATE
Authorization: Basic admin:djdjdj

### read table / fields
GET http://localhost:8080/rest/jsonapi/northwind/CUSTOMERS?fields[ORDERS]=ORDER_DATE,REQUIRED_DATE
Authorization: Basic admin:djdjdj

### read record / limit / offset
GET http://localhost:8080/rest/jsonapi/northwind/ORDERS?page[limit]=2&page[offset]=1
Authorization: Basic admin:djdjdj

